### ISSUE TITLE
Seed - while rewriting, it moves outside of the application.

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#101]

**Comment by HODLERTECH** [comment]
After seed prescription and clicking "Enter", is there an error message "This word do not exist in wordlist"
Program should to block "Enter" button.

**Comment by tendersoft-mjb** [comment]
The description is not very clear about the proposed changes. Is this item about properly setting focus to input controls?

**Comment by DanielMazurFL4RE** [comment]
It's a bug of standard library
