### ISSUE TITLE
Encrypted QR Backup -  few changes

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#102]
1. QR backup should be generated as the png,  not the zip archive. Image should be displayed after being generated on the screen,
2. The name of the generated image with backup should contain same informations as HSB: Nameof the Wallet_GeneratingDate_timestamp.png
3. Add instructions to restore the backup from the QR Code to the image with the QR code.

Welcome. 
The above QR code is an encrypted backup of the HODLER Open Source Multi-Asset Wallet . In order to open it, you need to know the password set by the backup creator.

Below is a guide on how to restore your wallet:
1. Download the mobile version of the HODLER wallet at www.hodler.tech
2. Click "Add Account" >> "Restore from HODLER Encrypted QR code"
3. Scan the QR code above
4. Name the wallet in the "Account name" field and enter the wallet password in the "Enter password" field.

If the password you wrote is correct, the account will be added to the wallet and you will be able to use the funds accumulated on it.

We hope that you will like our program and you will stay with us!

Greetings - HODLER.TECH Team

**Comment by Fl4reTobiasH** [comment]
New, better layout of the instruction needed
