### ISSUE TITLE
Change the location of the app files from %appdata% to %appdata%/hodlertech/

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#103]
![giphy](https://user-images.githubusercontent.com/36729396/48277505-2ccb4800-e44b-11e8-8ec0-ec2d7869f89b.gif)

**Comment by Fl4reTobiasH** [comment]
Old files are moved to new localization %appdata%/hodlertech
