### ISSUE TITLE
Balance synchronization right after transaction

### ISSUE THREAD

**Issue by Fl4reTobiasH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#119]
1. User sends eg Bitcoin
2. By clicking OK on this screen:
![image](https://user-images.githubusercontent.com/45454639/49331623-90571a00-f5a0-11e8-9bbe-f74cd7e932b7.png)
the user initiates the synchronization of the coin being sent

**Comment by tendersoft-mjb** [comment]
The description is not exactrly clear about the intent.

What is the expected behavior?

Should the app initiate a balance syncronization after the user presses OK?

**Comment by Fl4reTobiasH** [comment]
> Should the app initiate a balance syncronization after the user presses OK?
Yes, exactly, but only sent token/coin should be synchronized to display of the correct balance faster
