### ISSUE TITLE
Make FileManager platform independed

### ISSUE THREAD

**Issue by DanielMazurFL4RE** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#124]
Put logic of drawing and mantaining files onto higher layer than I/O & files detecting it in operating system. Now, these layers are toghether so coding new OS support is harder

**Comment by tendersoft-mjb** [comment]
The app should (if possible) use the system's file/storage manager. We should avoid dedicating resources to re-inventing core system functionality already preset on the target OS.

**Comment by DanielMazurFL4RE** [comment]
Android and iOS do not have storage managers in their SDK. Every app should have own, made for their requirements, like Gallery app or Downloads app

**Comment by DanielMazurFL4RE** [comment]
OS layer is divided from FileManager, issue may be closed
