### ISSUE TITLE
Problem with "change" 

### ISSUE THREAD

**Issue by Fl4reTobiasH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#131]
1. I have 200usd on my wallet
2. I'm sending 100USD
3 I see 0 USD in my wallet for few minutes

change
![image](https://user-images.githubusercontent.com/45454639/49687544-b894ca80-fb04-11e8-8d15-028d200757c2.png)

**Comment by DanielMazurFL4RE** [comment]
https://github.com/HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet/blob/master/HODLER_Multiplatform_Win_And_iOS_Linux/additionalUnits/AccountData.pas#L140

add 
if unconfirmed > 0 then [..]

**Comment by DanielMazurFL4RE** [comment]
Do not sum confirmed and unconfirmed together. Make a pending icon in main view
