### ISSUE TITLE
Version 0.4.x of Hodler PRO is marked as 0.2 like the last update i.e. no version change

### ISSUE THREAD

**Issue by tendersoft-mjb** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#155]
New version of Hodler OS is marked like the old version HODLEROS 0.2
Proper name should have template: _Hodler OS vx.y.z_ for example: **Hodler OS v4.3.1**

![image](https://user-images.githubusercontent.com/7294417/58192464-1ab34780-7cc1-11e9-9bed-2be5827c3422.png)

**Comment by Fl4reTobiasH** [comment]
Included in the current version of the updater
