### ISSUE TITLE
No check for sufficient battery level to update Hodler OS on Hodler PRO

### ISSUE THREAD

**Issue by tendersoft-mjb** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#157]
The downloader / installer does not seem to check if there is enough battery for the download/install procedure to complete successfully. It should recommend at least 50% or a plugged power cable for the duration of the version upgrade.

**Comment by Fl4reTobiasH** [comment]
30% battery or 20% battery is required if connected.
