### ISSUE TITLE
how to change app language ?? and make it right to left 

### ISSUE THREAD

**Issue by subzero1234lx** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#159]
hi 
i am interested in your work and it is so good 
if i want to change a language to Arabic for example and i want to make it right to left order 
how can i do this changes and i want to change it some how that if you will upgrade it 
it has no problem for me to upgrade 
sorry about poor english and thanks

**Comment by DanielMazurFL4RE** [comment]
We will consider it in upcoming update with brand new layout. At this moment changing the layout in RTL mode is impossible
