### ISSUE TITLE
Get many Errors when compiling

### ISSUE THREAD

**Issue by subzero1234lx** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#160]
hi
first please write a installation help file to help people like me who wants to compile it .
when i want to compile a project i get this error 5 times and many many warrnings.

[dcc64 Error] AccountRelated.pas(1309): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments

[dcc64 Error] AccountRelated.pas(1127): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments

and this error :

[dcc64 Error] AccountRelated.pas(215): E2010 Incompatible types: 'AnsiString' and 'Int64'

an other question 
what is these  "private_key.key" and "public_key.key" files used for? and why these are missing ?
i personaly make this files in project root and in both of them i wrote a random number . is that correct or no?

so please help me compile it...

**Comment by DanielMazurFL4RE** [comment]
Hello, which version of Delphi did you tried? Please try with 10.3.1

**Comment by subzero1234lx** [comment]
hi
i use this version of RAD:

Embarcadero® Delphi 10.3 Version 26.0.32429.4364 
Copyright © 2018 Embarcadero Technologies, Inc. All Rights Reserved.
and running win 7 64 bit

**Comment by subzero1234lx** [comment]
hi 
i test it with rad 10.3.2 and win 32 compiler and i receve exact same errors
please give me some hand and help me 
"_**To compile just select platform and press SHIFT+CTRL+F9**_"  realy does not work at all

**Comment by n074v41l4bl34u** [comment]
I doubt the Team will be able to assist you much further. They are swamped with work on the upcoming release. You have the code, you're the dev - figure it out.

**Comment by subzero1234lx** [comment]
only use of this issues is for testing and results in your opinion
no questions is nececery to be  answered 
it means u do not want or like to any body can compile this code 
it even have a syntax error and missing files
why?
every open source program have a full help file for compiling and contributing 
any way 
have a good open source project!!!
