### ISSUE TITLE
IS THERE ANY BODY EXCEPT DEVELOPER TEAM THAT CAN COMPILE SOURCE CODE????????!!!!!

### ISSUE THREAD

**Issue by subzero1234lx** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#161]
HI EVERY BODY ( IF ANY BODY IS HERE)
IS THERE ANY BODY EXCEPT DEVELOPER TEAM THAT CAN COMPILE SOURCE CODE????????!!!!!
AND IS THERE ANY BODY HAVE SOME ANSWER ME "_**WHY THIS OPEN SOURCE PROGRAM CAN NOT BE COMPILE**_" ???
I USED 
RAD 10.3  
RAD 10.3.1 
RAD 10.3.2 
WIN 7  64 BIT
WIN 10 64 BIT 
WIN 7 32 BIT 
AND EVERY TIME I GOT SAME ERRORS.
----------------------------------------
[dcc64 Error] AccountRelated.pas(1309): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments

[dcc64 Error] AccountRelated.pas(1127): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments

and this error :

[dcc64 Error] AccountRelated.pas(215): E2010 Incompatible types: 'AnsiString' and 'Int64'
--------------------------------------------
any help appreciate

**Comment by DanielMazurFL4RE** [comment]
Please compile under Win32 output, as I said before and use only 10.3.1
Errors above are result of your compilation as Win64 output

**Comment by subzero1234lx** [comment]
hi
tanks for your reply
finally after 5 days of working on it  i solve it
all errors related to this two missing files :

private_key.key
public_key.key
this two files are missing in repository and in misc.pas it need this files

const
  HODLER_URL: string = 'https://hodler1.nq.pl/';
  HODLER_URL2: string = 'https://hodlerstream.net/';
  HODLER_ETH: string = 'https://hodler2.nq.pl/';
  HODLER_ETH2: string = 'https://hodlernode.net/';
  API_PUB = {$I 'public_key.key' };
  API_PRIV = {$I 'private_key.key' };


at first i change this code to this and then those errors apear.
API_PUB = 0; // {$I 'public_key.key' };
API_PRIV = 1; //{$I 'private_key.key' };

i asked about it but u did not answered 
now i change it to this and every things works like a charm 
API_PUB = "aaaaaa" ; // {$I 'public_key.key' };
API_PRIV = "bbbbbb" ; //{$I 'private_key.key' };

thanks for your work but i wish project had a good help file 
it will help

**Comment by DanielMazurFL4RE** [comment]
Next time please read README carefully, because there was info about these files and how to obtain access to api
