### ISSUE TITLE
 Scaling fonts depending on the screen size of the smartphone.

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#59]
All information is generally too small in size (on a FullHD 5.15 "screen). On the HD Ready screen, some of the margins are too large and some information is truncated.

**Comment by DanielMazurFL4RE** [comment]
Please provide some screenshots

**Comment by HODLERTECH** [comment]
Converting the font size depending on the size of the smartphone.

**Comment by HODLERTECH** [comment]
Still not fixed on Hardware Wallet
