### ISSUE TITLE
HSB issue "invoke error, method not found"

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Open-Source-Multi-Asset-Wallet#72]
Android 5.1, smartphone: Oppo

The problem occurs on older smartphones, reported android 5.1 and 4.4

![image](https://user-images.githubusercontent.com/36729396/46602645-05522a00-caf1-11e8-8138-760873f0a1ee.png)

https://forums.embarcadero.com/message.jspa?messageID=900190

**Comment by DanielMazurFL4RE** [comment]
https://developer.android.com/training/permissions/requesting

It seems that apps below 6.0 version of Android does not have a requestPermission function so there is a need of checking OS version (<6) before call

**Comment by HODLERTECH** [comment]
The problem still occurs, the latest report from Android 5.0
![image](https://user-images.githubusercontent.com/36729396/48016110-fe87f880-e12a-11e8-8340-a9ed3fe2df7d.png)
